language: csharp
mono: none
sudo: required
dist: trusty
dotnet: 2.1.301
addons:
  branches:
    - master
script:
  - dotnet restore test/MobilePhoneRegionTest
  - dotnet test test/MobilePhoneRegionTest
